# Usa a imagem oficial do Python como base
FROM python:3.14.7-slim

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia o arquivo de dependências para o container
COPY requirements.txt .

# Instala as dependências do projeto
RUN pip install --no-cache-dir -r requirements.txt

# Copia o resto do código da aplicação para o container
COPY . .

# Comando padrão para executar a aplicação
CMD ["python", "app.py"]